name: CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci --force
            - name: Lint TypeScript
              run: npm run lint:ts
              if: always()
            - name: Lint CSS
              run: npm run lint:scss
              if: always()
            - name: Build
              run: npm run build:prod

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci --force
            - name: Build
              run: npm run build:prod
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: build
                  clean: true
                  target-folder: .
                  token: ${{ secrets.GITHUB_TOKEN }}
